/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}', './app/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        ds: {
          bg: '#1C2129',
          canvas: '#202630',
          surface: '#252B35',
          elevated: '#2B3340',
          field: '#303846',
          border: '#343D4B',
          hairline: '#29313C',
          text: '#F4F6FA',
          muted: '#A8B0BE',
          subtle: '#768191',
          disabled: '#525C6B',
          accent: '#72A8FF',
          'accent-soft': '#1D3B5F',
          'accent-pressed': '#1F78E5',
          today: '#FFD23F',
          upcoming: '#FF4F7A',
          anytime: '#56D6C2',
          logbook: '#36C978',
          someday: '#CFC6A4',
          danger: '#FF5A66',
        },
      },
      borderRadius: {
        ds: '14px',
        'ds-input': '10px',
        'ds-card': '18px',
        'ds-panel': '22px',
        'ds-pill': '999px',
      },
      spacing: {
        'ds-screen': '24px',
        'ds-card': '20px',
        'ds-row': '14px',
        'ds-tab': '88px',
      },
      fontSize: {
        'vb-xs': ['11px', { lineHeight: '14px', letterSpacing: '0em' }],
        'vb-sm': ['13px', { lineHeight: '18px', letterSpacing: '0em' }],
        'vb-base': ['15px', { lineHeight: '20px', letterSpacing: '0em' }],
        'vb-md': ['17px', { lineHeight: '22px', letterSpacing: '0em' }],
        'vb-lg': ['19px', { lineHeight: '24px', letterSpacing: '0em' }],
        'vb-xl': ['24px', { lineHeight: '30px', letterSpacing: '0em' }],
      },
      fontFamily: {
        sans: ['Inter_400Regular'],
        inter: ['Inter_400Regular'],
        'inter-medium': ['Inter_500Medium'],
        'inter-semibold': ['Inter_600SemiBold'],
        'inter-bold': ['Inter_700Bold'],
        'inter-black': ['Inter_900Black'],
      },
    },
  },
  plugins: [],
};
